### ISSUE TITLE
Define use of `executionMeta` field in Guard/Hooks interface

### ISSUE THREAD

**Issue by akshay-ap** [safe-global/safe-core-protocol-specs#10]
With current protocol spec, it is not clear what information is passed in `executionMeta` field of Gaurd/hooks interface.
How should a guard/hook process this information?
https://github.com/5afe/safe-protocol-specs/tree/main/components#guards-hooks

**Comment by rmeissner** [comment]
The execution meta should contain information about the execution flow. I.e. if it is triggered via the multisig flow of Safe it should contain information for this flow. Or if it is a module flow, it should contain information about it (like the module address).
