### ISSUE TITLE
Regarding safety issues

### ISSUE THREAD

**Issue by 760644586** [safe-global/safe-core-protocol-specs#41]
If Gnosis Safe Deployer updates the contract with 0xd9Db270c1B5E3Bd161E8c8503c55cEABeE709552, will the deployed addresses be affected by the new contract

**Comment by 760644586** [comment]
I would like to know if our address is 100% secure and controllable

**Comment by 760644586** [comment]
If you update the contract, will you have control over my address

**Comment by mmv08** [comment]
Safe contracts are fully non-custodial, and no party controls or can modify them. Feel free to audit and read the code of the contract. It's verified on etherscan.
