### ISSUE TITLE
[Protocol Specs] The specs are missing the expected encoding for signature validators

### ISSUE THREAD

**Issue by mmv08** [safe-global/safe-core-protocol-specs#56]
I couldn't find this section from the implementation in the specs:
https://github.com/safe-global/safe-core-protocol/blob/feature-108-add-signature-validator/contracts/SignatureValidatorManager.sol#L95-L118

This should be mentioned in the specifications

**Comment by rmeissner** [comment]
For me this is an implementation detail, that is not necessarily related to the spec. As in the spec it just says "the protocol can handle this", while in the implementation we potentially use multiple contracts with internal routing to handle this.

**Comment by mmv08** [comment]
Understood, so this should be added to the core-protocol docs
